version: '3'

services:
  redis:
    image: bitnami/redis:latest
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis'
    networks:
      - app_network
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'

  postgresql:
    image: docker.io/bitnami/postgresql:16
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'POSTGRESQL_USERNAME=${POSTGRESQL_USER}'
      - 'POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}'
      - 'POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}'
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - postgresql
    networks:
      - app_network
    env_file:
      - .env

volumes:
  redis_data:
    driver: local
  postgresql_data:
    driver: local

networks:
  app_network:
    driver: bridge
